name: Stylecheck
on:
  pull_request:
    branches: [master]

jobs:
  stylecheck:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Get Changed Files
        id: get_changed_files
        uses: lots0logs/gh-action-get-changed-files@2.1.4
        with:
          token: ${{ github.token }}
      - name: Run vale
        uses: errata-ai/vale-action@master
        with:
          styles: https://github.com/errata-ai/Google/releases/latest/download/Google.zip
          config: https://raw.githubusercontent.com/blockstack/docs/master/.vale/vale.ini
          files: "${{ steps.get_changed_files.outputs.all }}"
          onlyAnnotateModifiedLines: true
        env:
          GITHUB_TOKEN: ${{ github.token }}
